-- 采购单及入库明细表，支撑供应商到库存的采购入库闭环。
USE `henfon-shop`;
CREATE TABLE IF NOT EXISTS inventory_purchase_order (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, purchase_no VARCHAR(64) NOT NULL, supplier_id BIGINT UNSIGNED NOT NULL,
 warehouse_id BIGINT UNSIGNED NOT NULL, status TINYINT UNSIGNED NOT NULL DEFAULT 0, total_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
 received_at DATETIME(3) DEFAULT NULL, created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
 is_deleted TINYINT UNSIGNED NOT NULL DEFAULT 0, version INT UNSIGNED NOT NULL DEFAULT 0, remark VARCHAR(500), PRIMARY KEY(id), UNIQUE KEY uk_inventory_purchase_no(purchase_no,is_deleted), KEY idx_inventory_purchase_status(status,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS inventory_purchase_item (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, purchase_order_id BIGINT UNSIGNED NOT NULL, product_id BIGINT UNSIGNED NOT NULL, sku_id BIGINT UNSIGNED NOT NULL,
 quantity INT UNSIGNED NOT NULL, received_quantity INT UNSIGNED NOT NULL DEFAULT 0, unit_price DECIMAL(18,2) NOT NULL DEFAULT 0, created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), is_deleted TINYINT UNSIGNED NOT NULL DEFAULT 0, version INT UNSIGNED NOT NULL DEFAULT 0, remark VARCHAR(500), PRIMARY KEY(id), KEY idx_inventory_purchase_item_order(purchase_order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
